<?php

return [
    // Cavite Cities
    'cities' => [
        'Alfonso' => ['zip' => '4123'],
        'Amadeo' => ['zip' => '4119'],
        'Bacoor' => ['zip' => '4102'],
        'Carmona' => ['zip' => '4116'],
        'Cavite City' => ['zip' => '4100'],
        'Dasmariñas' => ['zip' => '4114'],
        'General Emilio Aguinaldo' => ['zip' => '4124'],
        'General Mariano Alvarez' => ['zip' => '4117'],
        'General Trias' => ['zip' => '4107'],
        'Imus' => ['zip' => '4103'],
        'Indang' => ['zip' => '4122'],
        'Kawit' => ['zip' => '4104'],
        'Magallanes' => ['zip' => '4113'],
        'Maragondon' => ['zip' => '4112'],
        'Mendez' => ['zip' => '4151'],
        'Naic' => ['zip' => '4110'],
        'Noveleta' => ['zip' => '4105'],
        'Rosario' => ['zip' => '4106'],
        'Silang' => ['zip' => '4118'],
        'Tagaytay' => ['zip' => '4120'],
        'Tanza' => ['zip' => '4108'],
        'Ternate' => ['zip' => '4111'],
        'Trece Martires' => ['zip' => '4109'],
    ],

    // Selected barangays for major cities (you can expand these)
    'barangays' => [
        'Bacoor' => [
            'Alima',
            'Aniban I',
            'Aniban II',
            'Banalo',
            'Bayanan',
            'Campo Santo',
            'Daang Bukid',
            'Digman',
            'Dulong Bayan',
            'Habay I',
            'Habay II',
            'Kaingin',
            'Ligas I',
            'Ligas II',
            'Ligas III',
            'Mabolo I',
            'Mabolo II',
            'Maliksi I',
            'Maliksi II',
            'Maliksi III',
            'Molino I',
            'Molino II',
            'Molino III',
            'Molino IV',
            'Molino V',
            'Molino VI',
            'Molino VII',
            'Niog I',
            'Niog II',
            'Niog III',
            'Panapaan I',
            'Panapaan II',
            'Panapaan III',
            'Panapaan IV',
            'Queens Row Central',
            'Queens Row East',
            'Queens Row West',
            'Real I',
            'Real II',
            'Salinas I',
            'Salinas II',
            'Salinas III',
            'Salinas IV',
            'San Nicolas I',
            'San Nicolas II',
            'San Nicolas III',
            'Springville',
            'Tabing Dagat',
            'Talaba I',
            'Talaba II',
            'Talaba III',
            'Talaba IV',
            'Talaba V',
            'Talaba VI',
            'Talaba VII',
            'Zapote I',
            'Zapote II',
            'Zapote III',
            'Zapote IV',
            'Zapote V',
        ],
        'Dasmariñas' => [
            'Salitran I',
            'Salitran II',
            'Salitran III',
            'Salitran IV',
            'Sampaloc I',
            'Sampaloc II',
            'Sampaloc III',
            'Sampaloc IV',
            'Sampaloc V',
            'San Agustin I',
            'San Agustin II',
            'San Agustin III',
            'Victoria Reyes',
            'Zone I',
            'Zone II',
            'Zone III',
            'Zone IV',
        ],
        'Imus' => [
            'Alapan I-A',
            'Alapan I-B',
            'Alapan I-C',
            'Alapan II-A',
            'Alapan II-B',
            'Anabu I-A',
            'Anabu I-B',
            'Anabu I-C',
            'Anabu I-D',
            'Anabu I-E',
            'Anabu I-F',
            'Anabu I-G',
            'Anabu II-A',
            'Anabu II-B',
            'Anabu II-C',
            'Bayan Luma I',
            'Bayan Luma II',
            'Bayan Luma III',
            'Bucandala I',
        ],
        'Tagaytay' => [
            'Asisan',
            'Bagong Tubig',
            'Calabuso',
            'Dapdap East',
            'Dapdap West',
            'Francisco',
            'Guinhawa North',
            'Guinhawa South',
            'Iruhin Central',
            'Iruhin East',
            'Iruhin South',
            'Iruhin West',
            'Kaybagal Central',
            'Kaybagal North',
            'Kaybagal South',
            'Mag-Asawang Ilat',
            'Maharlika East',
            'Maharlika West',
            'Maitim 2nd Central',
            'Maitim 2nd East',
            'Maitim 2nd West',
            'Mendez Crossing East',
            'Mendez Crossing West',
            'Neogan',
            'Patutong Malaki North',
            'Patutong Malaki South',
            'Sambong',
            'San Jose',
            'Silang Crossing East',
            'Silang Crossing West',
            'Sungay East',
            'Sungay West',
            'Tolentino East',
            'Tolentino West',
            'Zambal',
        ],
        'General Trias' => [
            'Alingaro',
            'Arnaldo',
            'Bacao I',
            'Bacao II',
            'Bagumbayan',
            'Biclatan',
            'Buenavista I',
            'Buenavista II',
            'Buenavista III',
            'Corregidor',
            'Dulong Bayan',
            'Gov. Ferrer',
            'Javalera',
            'Manggahan',
            'Navarro',
            'Ninety Sixth',
            'Panungyanan',
            'Pasong Camachile I',
            'Pasong Camachile II',
            'Pasong Kawayan I',
            'Pasong Kawayan II',
            'Pinagtipunan',
            'Prinza',
            'Sampalucan',
            'San Francisco',
            'San Gabriel',
            'San Juan I',
            'San Juan II',
            'Santa Clara',
            'Santiago',
            'Tapia',
            'Tejero',
            'Vibora',
        ],
    ],
];
